config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :users
end

app/models/product.rb
class Product < ActiveRecord::Base

  ## VALIDATIONS ##
  validates :name, :description, :price, presence: true
  validates :price, numericality: {allow_blank: true}
  has_attached_file :image, styles: {meduim: "300x300>", thumb: "100x100>"}
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/profile.rb
class Profile < ActiveRecord::Base

  ## VALIDATIONS ##
  validates :nickname, :dob, :phone, presence: true

  ## ASSOCIATIONS ##
  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base

  include ActiveModel::SecurePassword
  has_secure_password

  ## ASSOCIATIONS ##
  has_one :profile

  ## VALIDATIONS ##
  validates :name, :email, presence: true
  validates_associated :profile

  ## NESTED ATTRIBUTES ##
  accepts_nested_attributes_for :profile

  ## CALLBACKS ##
  before_validation :generate_temp_password, on: :create
  after_create :send_welcome_email

  ## INSTANCE METHODS ##

  ## PRIVATE METHODS ##
  private

  def generate_temp_password
    self.password = self.password_confirmation = SecureRandom.hex(4)
  end

  def send_welcome_email
    UserMailer.send_welcome_email(self, self.password).deliver
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
		@products = Product.all
	end

	def new
		@product = Product.new
	end

	def show
		@product = Product.find(params[:id])
	end

	def create
		@product = Product.new(product_params)
		if @product.save
			redirect_to products_path
		else
			render :new
		end
	end

	def edit
		@product = Product.find(params[:id])
	end

	def update
		@product = Product.find(params[:id])
	  if @product.update_attributes(product_params)
	    # Handle a successful update.
	    redirect_to products_path
		else
	    render 'edit'
	  end
	end

	def destroy
    Product.find(params[:id]).destroy
    redirect_to products_path
	end

	private

	def product_params
		params[:product].permit(:name, :description, :price, :image)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path
    else
      puts @user.errors.inspect
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, profile_attributes: profile_params)
  end

  def profile_params
    [:nickname, :bio, :phone, :dob]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def inline_error(obj, attrib)
		obj.errors[attrib].to_sentence
	end

  def setup_obj(obj, attrib)
    obj.send(attrib) || obj.send("build_#{attrib.to_s}")
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Depot
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield

app/views/products/edit.html.haml
%div.container
	%h1 Update Product
	= form_for @product, :html => {:class => 'form-horizontal' }, multipart: true do |f|
		%div.form-group
			= f.label :name, class: 'col-sm-2 control-label'
			.col-sm-4
				= f.text_field :name, class: 'form-control'
		%div.form-group
			= f.label :description, class: 'col-sm-2 control-label'
			.col-sm-4
				= f.text_area :description, class: 'form-control'
		%div.form-group
			= f.label :price, class: 'col-sm-2 control-label'
			.col-sm-4
				= f.text_field :price, class: 'form-control'
		%div.form-group
			= f.label :file, class: 'col-sm-2 control-label'
			.col-sm-4
				= f.file_field :file
		%div.form-group
			.col-sm-offset-2.col-sm-10
				= f.submit "Update Product", class: "btn btn-default"
	= link_to 'back', products_path, :class => 'btn btn-primary'

app/views/products/index.html.haml
%div.container
	%h1 All Products	
	%table.table.table-hover
		%thead
			%tr
				%th
					ID
				%th
					Product Name
				%th
					Description
				%th
					Price
				%th
					Actions
		%tbody
			- @products.each do |product|
				%tr
					%td
						= product.id
					%td
						= link_to product.name, product_path(product)
					%td 
						= product.description
					%td
						= product.price
					%td
						= link_to 'Edit', edit_product_path(product), :class => 'btn btn-default'
						= link_to 'Delete', product_path(product), :method => :delete, data: {:confirm => 'Are you sure ?'}, :class => 'btn btn-danger'
	= link_to 'New Product', new_product_path, :class => 'btn btn-primary'

app/views/products/new.html.haml
%div.container
	%h1 New Product
	= form_for @product, :html => {:class => 'form-horizontal' }, multipart: true do |f|
		- if @product.errors.any?
			%div.bg-background
				= pluralize(@product.errors.count, 'error')
		%div.form-group
			= f.label :name, class: 'col-sm-2 control-label'
			.col-sm-4
				= f.text_field :name, class: 'form-control'
				%h6.alert-danger.error= inline_error(@product, :name)
		%div.form-group
			= f.label :description, class: 'col-sm-2 control-label'
			.col-sm-4
				= f.text_area :description, class: 'form-control'
				%h6.alert-danger.error=  inline_error(@product, :description)
		%div.form-group
			= f.label :price, class: 'col-sm-2 control-label'
			.col-sm-4
				= f.text_field :price, class: 'form-control'
				%h6.alert-danger.error=  inline_error(@product, :price)
		%div.form-group
			= f.label :file, class: 'col-sm-2 control-label'
			.col-sm-4
				= f.file_field :file
				%h6.alert-danger.error=  inline_error(@product, :file)
		%div.form-group
			.col-sm-offset-2.col-sm-10
				= f.submit "Create Product", class: "btn btn-default"
	= link_to 'back', products_path, :class => 'btn btn-primary'

app/views/products/show.html.haml
%div

	= @product.name

app/views/users/new.html.haml
%div.container
  %h1 New User
  = form_for @user, html: {class: 'form-horizontal' }, multipart: true do |f|
    - if @user.errors.any?
      %div.bg-background
        = pluralize(@user.errors.count, 'error')
    %div.form-group
      = f.label :name, class: 'col-sm-2 control-label'
      .col-sm-4
        = f.text_field :name, class: 'form-control'
        %h6.alert-danger.error= inline_error(@user, :name)
    %div.form-group
      = f.label :email, class: 'col-sm-2 control-label'
      .col-sm-4
        = f.text_field :email, class: 'form-control'
        %h6.alert-danger.error= inline_error(@user, :email)
    = f.fields_for :profile, setup_obj(@user, :profile) do |p|
      %div.form-group
        = p.label :nickname, class: 'col-sm-2 control-label'
        .col-sm-4
          = p.text_field :nickname, class: 'form-control'
          %h6.alert-danger.error= inline_error(p.object, :nickname)
      %div.form-group
        = p.label :bio, class: 'col-sm-2 control-label'
        .col-sm-4
          = p.text_area :bio, class: 'form-control'
          %h6.alert-danger.error= inline_error(p.object, :bio)
      %div.form-group
        = p.label :dob, class: 'col-sm-2 control-label'
        .col-sm-4
          = p.date_select :dob, class: 'form-control'
          %h6.alert-danger.error= inline_error(p.object, :dob)
      %div.form-group
        = p.label :phone, class: 'col-sm-2 control-label'
        .col-sm-4
          = p.text_field :phone, class: 'form-control'
          %h6.alert-danger.error= inline_error(p.object, :phone)
    %div.form-group
      .col-sm-offset-2.col-sm-10
        = f.submit "Create User", class: "btn btn-default"